export const category: string[] = [
    'Algorythms',
    'Android',
    'Archtecture',
    'C#',
    'C++',
    'CSS_HTML',
    'DataBases',
    'Java',
    'JavaScript',
    'Operating Systems',
    'PHP',
    'Phyton',
    'Other',
];